-- Yaddii Marketplace — vehicle makes & models seed
-- Curated for Egypt classifieds (~58 makes, ~618 models)
-- Safe to re-run: skips existing makes and models.
--
-- Run in Supabase SQL Editor AFTER schema.sql
-- Regenerate: node supabase/scripts/generate-vehicle-seed.mjs

-- ---------------------------------------------------------------------------
-- Makes
-- ---------------------------------------------------------------------------
insert into public.makes (name)
values
  ('Alfa Romeo'),
  ('Audi'),
  ('BAIC'),
  ('BMW'),
  ('BYD'),
  ('Cadillac'),
  ('Changan'),
  ('Chery'),
  ('Chevrolet'),
  ('Chrysler'),
  ('Citroën'),
  ('Daewoo'),
  ('Dodge'),
  ('Dongfeng'),
  ('DS'),
  ('Exeed'),
  ('FAW'),
  ('Fiat'),
  ('Ford'),
  ('Geely'),
  ('Genesis'),
  ('GMC'),
  ('GWM'),
  ('Haval'),
  ('Honda'),
  ('Hyundai'),
  ('Infiniti'),
  ('Isuzu'),
  ('JAC'),
  ('Jeep'),
  ('Jetour'),
  ('Kia'),
  ('Lada'),
  ('Land Rover'),
  ('Lexus'),
  ('Lincoln'),
  ('Mahindra'),
  ('Mazda'),
  ('Mercedes'),
  ('MG'),
  ('Mini'),
  ('Mitsubishi'),
  ('Nissan'),
  ('Opel'),
  ('Peugeot'),
  ('Porsche'),
  ('Proton'),
  ('Ram'),
  ('Renault'),
  ('Seat'),
  ('Skoda'),
  ('SsangYong'),
  ('Subaru'),
  ('Suzuki'),
  ('Tesla'),
  ('Toyota'),
  ('Volkswagen'),
  ('Volvo')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- Models (linked by make name)
-- ---------------------------------------------------------------------------
with model_data (make_name, model_name) as (
  values
  ('Alfa Romeo', 'Giulia'),
  ('Alfa Romeo', 'Stelvio'),
  ('Alfa Romeo', 'Giulietta'),
  ('Alfa Romeo', 'MiTo'),
  ('Alfa Romeo', 'Other'),
  ('Audi', 'A1'),
  ('Audi', 'A3'),
  ('Audi', 'A4'),
  ('Audi', 'A5'),
  ('Audi', 'A6'),
  ('Audi', 'A7'),
  ('Audi', 'A8'),
  ('Audi', 'Q2'),
  ('Audi', 'Q3'),
  ('Audi', 'Q5'),
  ('Audi', 'Q7'),
  ('Audi', 'Q8'),
  ('Audi', 'TT'),
  ('Audi', 'R8'),
  ('Audi', 'e-tron'),
  ('Audi', 'e-tron GT'),
  ('Audi', 'RS3'),
  ('Audi', 'RS5'),
  ('Audi', 'RS6'),
  ('Audi', 'RS7'),
  ('Audi', 'S3'),
  ('Audi', 'S4'),
  ('Audi', 'Other'),
  ('BAIC', 'X25'),
  ('BAIC', 'X35'),
  ('BAIC', 'X55'),
  ('BAIC', 'BJ40'),
  ('BAIC', 'Other'),
  ('BMW', '1 Series'),
  ('BMW', '2 Series'),
  ('BMW', '3 Series'),
  ('BMW', '4 Series'),
  ('BMW', '5 Series'),
  ('BMW', '6 Series'),
  ('BMW', '7 Series'),
  ('BMW', '8 Series'),
  ('BMW', 'X1'),
  ('BMW', 'X2'),
  ('BMW', 'X3'),
  ('BMW', 'X4'),
  ('BMW', 'X5'),
  ('BMW', 'X6'),
  ('BMW', 'X7'),
  ('BMW', 'Z4'),
  ('BMW', 'i3'),
  ('BMW', 'i4'),
  ('BMW', 'iX'),
  ('BMW', 'iX3'),
  ('BMW', 'M2'),
  ('BMW', 'M3'),
  ('BMW', 'M4'),
  ('BMW', 'M5'),
  ('BMW', 'Other'),
  ('BYD', 'F0'),
  ('BYD', 'F3'),
  ('BYD', 'F6'),
  ('BYD', 'S6'),
  ('BYD', 'S7'),
  ('BYD', 'Han'),
  ('BYD', 'Tang'),
  ('BYD', 'Song'),
  ('BYD', 'Song Plus'),
  ('BYD', 'Atto 3'),
  ('BYD', 'Seal'),
  ('BYD', 'Dolphin'),
  ('BYD', 'Yuan Plus'),
  ('BYD', 'Qin'),
  ('BYD', 'Other'),
  ('Cadillac', 'Escalade'),
  ('Cadillac', 'XT4'),
  ('Cadillac', 'XT5'),
  ('Cadillac', 'XT6'),
  ('Cadillac', 'CT4'),
  ('Cadillac', 'CT5'),
  ('Cadillac', 'CT6'),
  ('Cadillac', 'Other'),
  ('Changan', 'Alsvin'),
  ('Changan', 'Eado'),
  ('Changan', 'CS35'),
  ('Changan', 'CS55'),
  ('Changan', 'CS75'),
  ('Changan', 'CS95'),
  ('Changan', 'Other'),
  ('Chery', 'QQ'),
  ('Chery', 'Tiggo 2'),
  ('Chery', 'Tiggo 3'),
  ('Chery', 'Tiggo 4'),
  ('Chery', 'Tiggo 5'),
  ('Chery', 'Tiggo 7'),
  ('Chery', 'Tiggo 8'),
  ('Chery', 'Arrizo 5'),
  ('Chery', 'Arrizo 6'),
  ('Chery', 'Arrizo 8'),
  ('Chery', 'Other'),
  ('Chevrolet', 'Optra'),
  ('Chevrolet', 'Lanos'),
  ('Chevrolet', 'Aveo'),
  ('Chevrolet', 'Cruze'),
  ('Chevrolet', 'Malibu'),
  ('Chevrolet', 'Spark'),
  ('Chevrolet', 'Captiva'),
  ('Chevrolet', 'Trax'),
  ('Chevrolet', 'Equinox'),
  ('Chevrolet', 'Tahoe'),
  ('Chevrolet', 'Suburban'),
  ('Chevrolet', 'Silverado'),
  ('Chevrolet', 'Camaro'),
  ('Chevrolet', 'Corvette'),
  ('Chevrolet', 'Blazer'),
  ('Chevrolet', 'Traverse'),
  ('Chevrolet', 'Impala'),
  ('Chevrolet', 'Trailblazer'),
  ('Chevrolet', 'Colorado'),
  ('Chevrolet', 'Bolt'),
  ('Chevrolet', 'Nubira'),
  ('Chevrolet', 'Epica'),
  ('Chevrolet', 'Alero'),
  ('Chevrolet', 'Other'),
  ('Chrysler', '300C'),
  ('Chrysler', 'Pacifica'),
  ('Chrysler', 'Voyager'),
  ('Chrysler', 'Sebring'),
  ('Chrysler', 'Other'),
  ('Citroën', 'C3'),
  ('Citroën', 'C4'),
  ('Citroën', 'C5'),
  ('Citroën', 'C-Elysee'),
  ('Citroën', 'Berlingo'),
  ('Citroën', 'C3 Aircross'),
  ('Citroën', 'C5 Aircross'),
  ('Citroën', 'DS3'),
  ('Citroën', 'Xsara'),
  ('Citroën', 'C4 Picasso'),
  ('Citroën', 'C8'),
  ('Citroën', 'Saxo'),
  ('Citroën', 'Other'),
  ('Daewoo', 'Lanos'),
  ('Daewoo', 'Nubira'),
  ('Daewoo', 'Matiz'),
  ('Daewoo', 'Leganza'),
  ('Daewoo', 'Other'),
  ('Dodge', 'Charger'),
  ('Dodge', 'Challenger'),
  ('Dodge', 'Durango'),
  ('Dodge', 'Ram 1500'),
  ('Dodge', 'Journey'),
  ('Dodge', 'Neon'),
  ('Dodge', 'Other'),
  ('Dongfeng', 'Shine Max'),
  ('Dongfeng', 'Huge'),
  ('Dongfeng', 'Other'),
  ('DS', 'DS 3'),
  ('DS', 'DS 4'),
  ('DS', 'DS 7'),
  ('DS', 'DS 9'),
  ('DS', 'Other'),
  ('Exeed', 'TXL'),
  ('Exeed', 'VX'),
  ('Exeed', 'LX'),
  ('Exeed', 'Other'),
  ('FAW', 'Bestune T77'),
  ('FAW', 'Bestune T99'),
  ('FAW', 'Other'),
  ('Fiat', '500'),
  ('Fiat', 'Panda'),
  ('Fiat', 'Tipo'),
  ('Fiat', 'Linea'),
  ('Fiat', 'Punto'),
  ('Fiat', '500X'),
  ('Fiat', 'Doblo'),
  ('Fiat', 'Other'),
  ('Ford', 'Focus'),
  ('Ford', 'Fiesta'),
  ('Ford', 'Fusion'),
  ('Ford', 'Mondeo'),
  ('Ford', 'Mustang'),
  ('Ford', 'Explorer'),
  ('Ford', 'Expedition'),
  ('Ford', 'Escape'),
  ('Ford', 'Edge'),
  ('Ford', 'Bronco'),
  ('Ford', 'Ranger'),
  ('Ford', 'F-150'),
  ('Ford', 'EcoSport'),
  ('Ford', 'Territory'),
  ('Ford', 'Everest'),
  ('Ford', 'Transit'),
  ('Ford', 'Other'),
  ('Geely', 'Emgrand'),
  ('Geely', 'Coolray'),
  ('Geely', 'Azkarra'),
  ('Geely', 'Okavango'),
  ('Geely', 'Monjaro'),
  ('Geely', 'Geometry C'),
  ('Geely', 'GC6'),
  ('Geely', 'CK'),
  ('Geely', 'Other'),
  ('Genesis', 'G70'),
  ('Genesis', 'G80'),
  ('Genesis', 'G90'),
  ('Genesis', 'GV60'),
  ('Genesis', 'GV70'),
  ('Genesis', 'GV80'),
  ('Genesis', 'Other'),
  ('GMC', 'Yukon'),
  ('GMC', 'Sierra'),
  ('GMC', 'Terrain'),
  ('GMC', 'Acadia'),
  ('GMC', 'Canyon'),
  ('GMC', 'Other'),
  ('GWM', 'Haval H6'),
  ('GWM', 'Tank 300'),
  ('GWM', 'Tank 500'),
  ('GWM', 'Wingle'),
  ('GWM', 'Poer'),
  ('GWM', 'Other'),
  ('Haval', 'H2'),
  ('Haval', 'H6'),
  ('Haval', 'H9'),
  ('Haval', 'Jolion'),
  ('Haval', 'Dargo'),
  ('Haval', 'Other'),
  ('Honda', 'City'),
  ('Honda', 'Civic'),
  ('Honda', 'Accord'),
  ('Honda', 'CR-V'),
  ('Honda', 'HR-V'),
  ('Honda', 'Pilot'),
  ('Honda', 'Odyssey'),
  ('Honda', 'Jazz'),
  ('Honda', 'Fit'),
  ('Honda', 'BR-V'),
  ('Honda', 'ZR-V'),
  ('Honda', 'e:Ny1'),
  ('Honda', 'Other'),
  ('Hyundai', 'Elantra'),
  ('Hyundai', 'Accent'),
  ('Hyundai', 'Sonata'),
  ('Hyundai', 'Tucson'),
  ('Hyundai', 'Creta'),
  ('Hyundai', 'Santa Fe'),
  ('Hyundai', 'Palisade'),
  ('Hyundai', 'Kona'),
  ('Hyundai', 'i10'),
  ('Hyundai', 'i20'),
  ('Hyundai', 'i30'),
  ('Hyundai', 'Azera'),
  ('Hyundai', 'Grand i10'),
  ('Hyundai', 'Verna'),
  ('Hyundai', 'H-1'),
  ('Hyundai', 'Staria'),
  ('Hyundai', 'Ioniq'),
  ('Hyundai', 'Ioniq 5'),
  ('Hyundai', 'Ioniq 6'),
  ('Hyundai', 'Venue'),
  ('Hyundai', 'Bayon'),
  ('Hyundai', 'Coupe'),
  ('Hyundai', 'Genesis Coupe'),
  ('Hyundai', 'Atos'),
  ('Hyundai', 'Matrix'),
  ('Hyundai', 'Getz'),
  ('Hyundai', 'Trajet'),
  ('Hyundai', 'Other'),
  ('Infiniti', 'Q30'),
  ('Infiniti', 'Q50'),
  ('Infiniti', 'Q60'),
  ('Infiniti', 'QX50'),
  ('Infiniti', 'QX55'),
  ('Infiniti', 'QX60'),
  ('Infiniti', 'QX80'),
  ('Infiniti', 'Other'),
  ('Isuzu', 'D-Max'),
  ('Isuzu', 'MU-X'),
  ('Isuzu', 'Other'),
  ('JAC', 'S2'),
  ('JAC', 'S3'),
  ('JAC', 'S4'),
  ('JAC', 'S5'),
  ('JAC', 'S7'),
  ('JAC', 'J7'),
  ('JAC', 'Other'),
  ('Jeep', 'Wrangler'),
  ('Jeep', 'Grand Cherokee'),
  ('Jeep', 'Cherokee'),
  ('Jeep', 'Compass'),
  ('Jeep', 'Renegade'),
  ('Jeep', 'Gladiator'),
  ('Jeep', 'Commander'),
  ('Jeep', 'Other'),
  ('Jetour', 'X70'),
  ('Jetour', 'X90'),
  ('Jetour', 'Dashing'),
  ('Jetour', 'T2'),
  ('Jetour', 'Other'),
  ('Kia', 'Cerato'),
  ('Kia', 'Optima'),
  ('Kia', 'K5'),
  ('Kia', 'Rio'),
  ('Kia', 'Picanto'),
  ('Kia', 'Sportage'),
  ('Kia', 'Sorento'),
  ('Kia', 'Carnival'),
  ('Kia', 'Soul'),
  ('Kia', 'Stinger'),
  ('Kia', 'Telluride'),
  ('Kia', 'Seltos'),
  ('Kia', 'Niro'),
  ('Kia', 'EV6'),
  ('Kia', 'Pegas'),
  ('Kia', 'Cadenza'),
  ('Kia', 'Mohave'),
  ('Kia', 'Carens'),
  ('Kia', 'Other'),
  ('Lada', 'Niva'),
  ('Lada', 'Granta'),
  ('Lada', 'Vesta'),
  ('Lada', 'Other'),
  ('Land Rover', 'Defender'),
  ('Land Rover', 'Discovery'),
  ('Land Rover', 'Discovery Sport'),
  ('Land Rover', 'Range Rover'),
  ('Land Rover', 'Range Rover Sport'),
  ('Land Rover', 'Range Rover Evoque'),
  ('Land Rover', 'Range Rover Velar'),
  ('Land Rover', 'Freelander'),
  ('Land Rover', 'Other'),
  ('Lexus', 'IS'),
  ('Lexus', 'ES'),
  ('Lexus', 'GS'),
  ('Lexus', 'LS'),
  ('Lexus', 'RC'),
  ('Lexus', 'LC'),
  ('Lexus', 'UX'),
  ('Lexus', 'NX'),
  ('Lexus', 'RX'),
  ('Lexus', 'GX'),
  ('Lexus', 'LX'),
  ('Lexus', 'Other'),
  ('Lincoln', 'Navigator'),
  ('Lincoln', 'Aviator'),
  ('Lincoln', 'Corsair'),
  ('Lincoln', 'Nautilus'),
  ('Lincoln', 'Other'),
  ('Mahindra', 'Scorpio'),
  ('Mahindra', 'XUV500'),
  ('Mahindra', 'XUV700'),
  ('Mahindra', 'Thar'),
  ('Mahindra', 'Other'),
  ('Mazda', 'Mazda 2'),
  ('Mazda', 'Mazda 3'),
  ('Mazda', 'Mazda 6'),
  ('Mazda', 'CX-3'),
  ('Mazda', 'CX-30'),
  ('Mazda', 'CX-5'),
  ('Mazda', 'CX-9'),
  ('Mazda', 'CX-60'),
  ('Mazda', 'CX-90'),
  ('Mazda', 'MX-5'),
  ('Mazda', 'BT-50'),
  ('Mazda', 'Other'),
  ('Mercedes', 'A-Class'),
  ('Mercedes', 'B-Class'),
  ('Mercedes', 'C-Class'),
  ('Mercedes', 'E-Class'),
  ('Mercedes', 'S-Class'),
  ('Mercedes', 'CLA'),
  ('Mercedes', 'CLS'),
  ('Mercedes', 'GLA'),
  ('Mercedes', 'GLB'),
  ('Mercedes', 'GLC'),
  ('Mercedes', 'GLE'),
  ('Mercedes', 'GLS'),
  ('Mercedes', 'G-Class'),
  ('Mercedes', 'AMG GT'),
  ('Mercedes', 'V-Class'),
  ('Mercedes', 'Sprinter'),
  ('Mercedes', 'Maybach S-Class'),
  ('Mercedes', 'EQA'),
  ('Mercedes', 'EQB'),
  ('Mercedes', 'EQC'),
  ('Mercedes', 'EQE'),
  ('Mercedes', 'EQS'),
  ('Mercedes', 'SL'),
  ('Mercedes', 'SLC'),
  ('Mercedes', 'Other'),
  ('MG', 'MG 3'),
  ('MG', 'MG 5'),
  ('MG', 'MG 6'),
  ('MG', 'MG ZS'),
  ('MG', 'MG HS'),
  ('MG', 'MG RX5'),
  ('MG', 'MG RX8'),
  ('MG', 'MG 4'),
  ('MG', 'MG GT'),
  ('MG', 'Other'),
  ('Mini', 'Cooper'),
  ('Mini', 'Cooper S'),
  ('Mini', 'Countryman'),
  ('Mini', 'Clubman'),
  ('Mini', 'Paceman'),
  ('Mini', 'Other'),
  ('Mitsubishi', 'Lancer'),
  ('Mitsubishi', 'Attrage'),
  ('Mitsubishi', 'Mirage'),
  ('Mitsubishi', 'ASX'),
  ('Mitsubishi', 'Outlander'),
  ('Mitsubishi', 'Pajero'),
  ('Mitsubishi', 'Montero'),
  ('Mitsubishi', 'Eclipse Cross'),
  ('Mitsubishi', 'Xpander'),
  ('Mitsubishi', 'L200'),
  ('Mitsubishi', 'Other'),
  ('Nissan', 'Sunny'),
  ('Nissan', 'Sentra'),
  ('Nissan', 'Altima'),
  ('Nissan', 'Maxima'),
  ('Nissan', 'Micra'),
  ('Nissan', 'Qashqai'),
  ('Nissan', 'X-Trail'),
  ('Nissan', 'Patrol'),
  ('Nissan', 'Kicks'),
  ('Nissan', 'Juke'),
  ('Nissan', 'Navara'),
  ('Nissan', 'Pathfinder'),
  ('Nissan', 'Murano'),
  ('Nissan', 'Armada'),
  ('Nissan', 'Tiida'),
  ('Nissan', 'Leaf'),
  ('Nissan', 'Ariya'),
  ('Nissan', '370Z'),
  ('Nissan', 'GT-R'),
  ('Nissan', 'Terrano'),
  ('Nissan', 'X-Terra'),
  ('Nissan', 'Teana'),
  ('Nissan', 'Primera'),
  ('Nissan', 'Pulsar'),
  ('Nissan', 'Cedric'),
  ('Nissan', 'Other'),
  ('Opel', 'Corsa'),
  ('Opel', 'Astra'),
  ('Opel', 'Insignia'),
  ('Opel', 'Mokka'),
  ('Opel', 'Crossland'),
  ('Opel', 'Grandland'),
  ('Opel', 'Zafira'),
  ('Opel', 'Vectra'),
  ('Opel', 'Meriva'),
  ('Opel', 'Adam'),
  ('Opel', 'Combo'),
  ('Opel', 'Omega'),
  ('Opel', 'Tigra'),
  ('Opel', 'Antara'),
  ('Opel', 'Agila'),
  ('Opel', 'Kadett'),
  ('Opel', 'Other'),
  ('Peugeot', '206'),
  ('Peugeot', '207'),
  ('Peugeot', '301'),
  ('Peugeot', '308'),
  ('Peugeot', '408'),
  ('Peugeot', '508'),
  ('Peugeot', '2008'),
  ('Peugeot', '3008'),
  ('Peugeot', '5008'),
  ('Peugeot', 'Partner'),
  ('Peugeot', 'Expert'),
  ('Peugeot', 'Boxer'),
  ('Peugeot', '405'),
  ('Peugeot', '406'),
  ('Peugeot', '607'),
  ('Peugeot', 'RCZ'),
  ('Peugeot', 'Other'),
  ('Porsche', '911'),
  ('Porsche', 'Cayenne'),
  ('Porsche', 'Macan'),
  ('Porsche', 'Panamera'),
  ('Porsche', 'Taycan'),
  ('Porsche', 'Boxster'),
  ('Porsche', 'Cayman'),
  ('Porsche', 'Other'),
  ('Proton', 'Saga'),
  ('Proton', 'Persona'),
  ('Proton', 'X50'),
  ('Proton', 'X70'),
  ('Proton', 'Other'),
  ('Ram', '1500'),
  ('Ram', '2500'),
  ('Ram', '3500'),
  ('Ram', 'Other'),
  ('Renault', 'Symbol'),
  ('Renault', 'Logan'),
  ('Renault', 'Sandero'),
  ('Renault', 'Megane'),
  ('Renault', 'Fluence'),
  ('Renault', 'Duster'),
  ('Renault', 'Koleos'),
  ('Renault', 'Captur'),
  ('Renault', 'Kadjar'),
  ('Renault', 'Scenic'),
  ('Renault', 'Clio'),
  ('Renault', 'Talisman'),
  ('Renault', 'Laguna'),
  ('Renault', 'Safrane'),
  ('Renault', 'Kangoo'),
  ('Renault', 'Twingo'),
  ('Renault', 'Other'),
  ('Seat', 'Ibiza'),
  ('Seat', 'Leon'),
  ('Seat', 'Arona'),
  ('Seat', 'Ateca'),
  ('Seat', 'Tarraco'),
  ('Seat', 'Toledo'),
  ('Seat', 'Other'),
  ('Skoda', 'Fabia'),
  ('Skoda', 'Octavia'),
  ('Skoda', 'Superb'),
  ('Skoda', 'Rapid'),
  ('Skoda', 'Kamiq'),
  ('Skoda', 'Karoq'),
  ('Skoda', 'Kodiaq'),
  ('Skoda', 'Scala'),
  ('Skoda', 'Enyaq'),
  ('Skoda', 'Other'),
  ('SsangYong', 'Tivoli'),
  ('SsangYong', 'Korando'),
  ('SsangYong', 'Rexton'),
  ('SsangYong', 'Musso'),
  ('SsangYong', 'Other'),
  ('Subaru', 'Impreza'),
  ('Subaru', 'Legacy'),
  ('Subaru', 'WRX'),
  ('Subaru', 'BRZ'),
  ('Subaru', 'Forester'),
  ('Subaru', 'Outback'),
  ('Subaru', 'Crosstrek'),
  ('Subaru', 'Ascent'),
  ('Subaru', 'XV'),
  ('Subaru', 'Other'),
  ('Suzuki', 'Swift'),
  ('Suzuki', 'Celerio'),
  ('Suzuki', 'Baleno'),
  ('Suzuki', 'Dzire'),
  ('Suzuki', 'Vitara'),
  ('Suzuki', 'Grand Vitara'),
  ('Suzuki', 'Jimny'),
  ('Suzuki', 'Ertiga'),
  ('Suzuki', 'Ciaz'),
  ('Suzuki', 'Alto'),
  ('Suzuki', 'Other'),
  ('Tesla', 'Model 3'),
  ('Tesla', 'Model Y'),
  ('Tesla', 'Model S'),
  ('Tesla', 'Model X'),
  ('Tesla', 'Cybertruck'),
  ('Tesla', 'Other'),
  ('Toyota', 'Corolla'),
  ('Toyota', 'Camry'),
  ('Toyota', 'Yaris'),
  ('Toyota', 'Fortuner'),
  ('Toyota', 'Hilux'),
  ('Toyota', 'Land Cruiser'),
  ('Toyota', 'RAV4'),
  ('Toyota', 'Highlander'),
  ('Toyota', 'Prius'),
  ('Toyota', 'Avanza'),
  ('Toyota', 'Rush'),
  ('Toyota', 'C-HR'),
  ('Toyota', 'Supra'),
  ('Toyota', 'GR86'),
  ('Toyota', 'Avalon'),
  ('Toyota', 'Sequoia'),
  ('Toyota', 'Tundra'),
  ('Toyota', 'Tacoma'),
  ('Toyota', '4Runner'),
  ('Toyota', 'Sienna'),
  ('Toyota', 'Innova'),
  ('Toyota', 'bZ4X'),
  ('Toyota', 'Corolla Cross'),
  ('Toyota', 'Urban Cruiser'),
  ('Toyota', 'FJ Cruiser'),
  ('Toyota', 'Crown'),
  ('Toyota', 'Venza'),
  ('Toyota', 'Matrix'),
  ('Toyota', 'Celica'),
  ('Toyota', 'MR2'),
  ('Toyota', 'Other'),
  ('Volkswagen', 'Golf'),
  ('Volkswagen', 'Polo'),
  ('Volkswagen', 'Passat'),
  ('Volkswagen', 'Jetta'),
  ('Volkswagen', 'Tiguan'),
  ('Volkswagen', 'Touareg'),
  ('Volkswagen', 'Teramont'),
  ('Volkswagen', 'T-Roc'),
  ('Volkswagen', 'Arteon'),
  ('Volkswagen', 'Beetle'),
  ('Volkswagen', 'Scirocco'),
  ('Volkswagen', 'ID.3'),
  ('Volkswagen', 'ID.4'),
  ('Volkswagen', 'ID.6'),
  ('Volkswagen', 'Amarok'),
  ('Volkswagen', 'Caddy'),
  ('Volkswagen', 'Transporter'),
  ('Volkswagen', 'Other'),
  ('Volvo', 'S60'),
  ('Volvo', 'S90'),
  ('Volvo', 'V60'),
  ('Volvo', 'V90'),
  ('Volvo', 'XC40'),
  ('Volvo', 'XC60'),
  ('Volvo', 'XC90'),
  ('Volvo', 'C40'),
  ('Volvo', 'Other')
)
insert into public.models (name, make_id)
select md.model_name, m.id
from model_data md
join public.makes m on m.name = md.make_name
where not exists (
  select 1
  from public.models mo
  where mo.make_id = m.id
    and mo.name = md.model_name
);

-- Optional: prevent duplicate models on future manual inserts
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'models_make_id_name_key'
      and conrelid = 'public.models'::regclass
  ) then
    alter table public.models
      add constraint models_make_id_name_key unique (make_id, name);
  end if;
end $$;

-- Summary
select
  (select count(*) from public.makes) as makes,
  (select count(*) from public.models) as models;
